<?php

namespace ContainerXJASATo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerUserSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Events\CustomerUserSubscriber' shared autowired service.
     *
     * @return \App\Events\CustomerUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Events/CustomerUserSubscriber.php';

        return $container->privates['App\\Events\\CustomerUserSubscriber'] = new \App\Events\CustomerUserSubscriber(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
