<?php

namespace ContainerXJASATo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrentUserExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Doctrine\CurrentUserExtension' shared autowired service.
     *
     * @return \App\Doctrine\CurrentUserExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Doctrine/CurrentUserExtension.php';

        return $container->privates['App\\Doctrine\\CurrentUserExtension'] = new \App\Doctrine\CurrentUserExtension(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->services['security.authorization_checker'] ?? $container->getSecurity_AuthorizationCheckerService()));
    }
}
